### ISSUE TITLE
Add a support/donate to spyder

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#10]
Can be on the home screen for now, and it does not need to do anything, but we need it to be there.

![image](https://cloud.githubusercontent.com/assets/3627835/17745627/340439e8-6472-11e6-8c9c-08041d006698.png)

**Comment by rlaverde** [comment]
This is related to https://github.com/spyder-ide/spyder/issues/1492

**Comment by dalthviz** [comment]
@ccordoba12 should we close this since we already have the button to opencollective?:

![imagen](https://user-images.githubusercontent.com/16781833/35662118-6334a3cc-06e4-11e8-8994-9f0404defdd3.png)

**Comment by ccordoba12** [comment]
The button already points to Open collective?

**Comment by dalthviz** [comment]
Yep, it was done at #62
