### ISSUE TITLE
Fix datetime format to be ISO 8601

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#117]
Currently, the dates on the blog posts are displayed in a strange format I've never seen in English:

> 23 February of 2018

Given the heavily international focus of the project, we should probably just stick with ISO 8601 YYYY-MM-DD [HH:MM:SS] date format (or, at least, a standard English form like February 23, 2018 or 23 February 2018 , for no other reason than English is the language of the blog). This should be simple to set in Lektor; I can do it if someone can point be toward where it was changed in the first place (as this is not the default to begin with).

**Comment by ccordoba12** [comment]
Sure, no problem with that.

**Comment by CAM-Gerlach** [comment]
This didn't end up being hard at all; I already did it on my own site. I just have to backport the changes to this one...

**Comment by ccordoba12** [comment]
Ok, please do.

**Comment by goanpeca** [comment]
Hi @CAM-Gerlach, has this been fixed ? Could you give us a hand?

Thanks!

**Comment by CAM-Gerlach** [comment]
Sorry, I fixed this shortly after filing this issue in the overhauled version of the theme. As soon as I port the site, this improvement along with many others will come for free; I apologize for the delay on that but once I get to it, it will be pretty straightforward to do.

**Comment by goanpeca** [comment]
Sure 👍
