### ISSUE TITLE
Harmonize blog body and header font sizes with docs

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#119]
As discussed in spyder-ide/spyder-docs#26 and implemented in spyder-ide/spyder-docs#48 , we probably should harmonize our blog header and body font sizes with that of our docs, for the same reasons that justified changing the fonts, including the serif heading font, to match. Furthermore, they are rather overly large as it is, making posts drag on longer and making the headings almost comically huge, so a little shrinkage wouldn't be a bad thing by itself either.

Therefore, I propose bumping the base blog font size down to 16px, to match the docs (bumped up just slightly) and the general web standard, and bumping the headers down to 2.4em, 1.8em and 1.5em to match the more reasonable 240%/180%/150% of the docs (which are very slightly larger than current docs ones to match the slightly increased normalized base font size). Ideally, it would be nice for this to be done for the release of the first blog post of the new series in #118 .

**Comment by ccordoba12** [comment]
On a second thought, I think it's ok for our blog and docs to have different styles.
