### ISSUE TITLE
Include blog in Planet SciPy

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/website-spyder#126]
The blog aggregator [Planet SciPy](http://planet.scipy.org) (which I think stands for Scientific Python, not just the scipy library) includes the old Spyder blog at http://spyder-ide.blogspot.com/ (even twice, for some reason), but not our shiny new blog. Not sure how popular Planet SciPy is, but it may get us some traffic.

**Comment by ccordoba12** [comment]
Great idea @jitseniesen! Could you help us with this one?

**Comment by jitseniesen** [comment]
I wrote to the maintainer of the website.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by jitseniesen** [comment]
We need to have an RSS feed to be included. Do we have one?

**Comment by ccordoba12** [comment]
I don't think so. @dalthviz, please investigate if Lektor can generate an RSS feed or how to do it by other means.

**Comment by dalthviz** [comment]
@ccordoba12 Lektor has a plugin for [Atom feeds](https://www.getlektor.com/plugins/lektor-atom/). @jitseniesen Could be valid with Atom feeds?

**Comment by jitseniesen** [comment]
@dalthviz Yes, an atom feed should work.

**Comment by CAM-Gerlach** [comment]
Included in the (much more popular and active) Planet Python; see python/planet#296 . @jitseniesen did you email Gael Varoquaux, as it said to do on the page, to ask them to remove the duplicates and add our new URL? The only email I could find was the generic firstname.lastname@inria.fr on [gael-varoquaux.info](http://gael-varoquaux.info/about.html) which seemed like it couldn't be correct.

**Comment by jitseniesen** [comment]
I did email him and got a reply, but it seems something went wrong. i'll contact him again.

**Comment by CAM-Gerlach** [comment]
Okay, thanks! I included this in spyder-ide/spyder-docs#39 for tracking purposes.

**Comment by CAM-Gerlach** [comment]
@jitseniesen Hey, any updates? This one of the last few blockers on spyder-ide/spyder-docs#39 , although if it appears the site is mostly defunct we can disinclude it there...

**Comment by jitseniesen** [comment]
The site has been down for two weeks or so, so I cannot check whether we are now included. I have also lost interest. I just stumbled on it, but it does not seem to have a big audience.

I'm closing this issue as no longer relevant.

**Comment by CAM-Gerlach** [comment]
Agreed; thanks!

**Comment by jitseniesen** [comment]
For what it's worth, the website is back up and our blog is included.

**Comment by CAM-Gerlach** [comment]
@jitseniesen Thanks for the update!
