### ISSUE TITLE
Include (reasonably-sized) "Download" and "Donate" buttons on the common header bar

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#134]
## Present situation

Somewhat related to some of @goanpeca 's suggestions in #109 , I'm not a big fan of the look of the overly large "donate" button, nor its positioning buried all the way down in the common footer, nor it making the footer awkwardly huge vertically (while cramped horizontally); not only does this harm the layout, but it makes it much less obvious to find immediately; meanwhile, the homepage has an essentially redundant "Donate" section that's basically just the button that could have been linked to directly, and only visible as a normal section label if the user doesn't scroll all the way down. 

Furthermore, an easy to access link to download Spyder, or at least to a page very concisely explaining how to do so with a large, obvious link (like [our current main page section](http://develop.spyder-ide.org/#fh5co-download)), is not available on sections of the Spyder site other than the homepage (docs, blog, future pages like FAQ, etc), and even on the homepage it is an undistinguished section link at the top.

## Strategic considerations

Overall, the two main actions we would like visitors to take to assure the survival, success and positive impact of Spyder and its broader open-source ecosystem is to A. Download and use Spyder, and B. Support our project financially (or otherwise); indeed, this is essentially the primary goal of our main site, and an important secondary objective of our sub-sites (Blog, Docs). Therefore, it follows that we want to make these two links as obvious and easily accessible as practicable without them being too visually "loud" and "in your face" , 

The current design succeeds at neither; the Donate button in the footer is obnoxiously huge and "blaring", yet is not even visible unless the user scrolls all the way to the bottom; meanwhile, a Download link isn't even present anywhere at all on the Blog, Docs, etc. 

## Proposal

Therefore, I suggest adding adding a "Donate" button that links directly to our OpenCollective [like the one NumFocus has](https://www.numfocus.org/) to the immediate right of the page/sub-site listing ("Blog", "Docs" etc) on all sites including the main page, while dropping the redundant "Donate" section link on the main page (possibly leaving the section itself). Meanwhile, we add "Download" as the left-most item of the page/sub-site listing listing on all pages but the homepage (since its already there), which behaves just like it already does on the homepage (linking to the Download section). This also synchronizes well with my suggestion on an alternate and more scalable way to handle the underlying situation motivating #133 .

**Comment by pradyot-09** [comment]
@ccordoba12 @goanpeca If this feature is still something you guys would like to have, you can assign it to me. I would be happy to contribute.

**Comment by CAM-Gerlach** [comment]
@pradyot-09 Thanks for your generous offer. However, the implementation is relatively trivial and I've already offer it as a simple config option in the overhaul of the lektor-icon theme I did, which I plan to port this site over to at some point in the near future (you can see it deployed on my [Star Fleet Tours site](https://www.star-fleet.tours/), for example). The majority of the effort with this is likely to be debating the UX and UI details and whether and what should be implemented, not the how.

**Comment by CAM-Gerlach** [comment]
The theme feature is specifically for links to other pages, and since we have download and donate _links_ at least in the navbar, and buttons on the page itself, seems we can close this now.
