### ISSUE TITLE
Create a transformer script to converto blog from nikola  (quansight labs website) to lektor (spyder website)

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#160]
Since we will for some time be cross posting on both the spyder blog and the quansight blog, we should create a small tool to make this easier. Since most of the time we start on the labs website, we should create a Nikola -> Lektor blog.

The structure is well defined and on the future we could have these posts be created by a github action.

**Comment by CAM-Gerlach** [comment]
Since we're no longer really cross-posting content like this, seems like this issue can be closed as outdated.
