### ISSUE TITLE
Pin to last version of atom that was using prividing the atom feed

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#161]

**Comment by goanpeca** [comment]
Pin `werkzeug<1.0` so that we can use an old version of werkzeug that has the atom feed provider.

**Comment by CAM-Gerlach** [comment]
The title is terribly garbled; from having suggested this I assume it should be something like

> Pin to last version of werkzeug that has the atom feed provider

At some point, the legacy Atom feed will have to be dropped so as to not be stuck on an ancient version of werkzeug; all major browsers except for IE have dropped support for RSS/Atom and the only real purpose was to include the blog on [Planet SciPy](https://planet.scipy.org/), which @jitseniesen mentioned was not very popular/widely used these days. This should be documented somewhere as part of this change.
