### ISSUE TITLE
Create 5-10 questions for the STXNEXT developer blog

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#166]
The idea is to use a testimonial plus some questions for Michał

---

## The testimonial

*Michał Wiśniewski*

In an era of a continuously growing demand for analysis of vast amounts of data, we are facing increasingly complex tasks to perform. Sure, we are not alone—there are many great tools designed for scientists and data analysts. We have NumPy, SciPy, Matplotlib, Pandas, and others. But, wouldn't it be nice to have one extra tool that could combine all the required packages into one compact working environment? Asking this question is precisely how my journey with Spyder began.

In my opinion, Spyder is the go-to-solution that helps to speed up the data analysis processes. For me, the biggest strength of this IDE is that it has all the benefits of Matlab/RStudio and makes them available to the Pythonista community. It provides us with an easy-to-organize workspace that accommodates code, visualizations and shell in just one window. The tab, called variable explorer, allows direct access to all data placed in the memory. 

Another cool feature is the tool’s integration with Jupyter. Just open and browse different notebooks without thinking about server-side and file paths. Want to run a single line of code or quickly check a chart update? IPython is on board and ready by default.

**Comment by goanpeca** [comment]
The company link is this one https://stxnext.com/ (forgot to add in the previous message)

**Comment by ccordoba12** [comment]
This was already addressed via email.
