### ISSUE TITLE
Minor followup changes after implementation of new theme

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#183]
* [x] Change FG color to theme default
* [x] Don't use different feature background on hover
* [x] Eliminate Spyder Reports from plugins
* [x] Fix order of donate and sponsors and nix sponsors from navbar to make it shorter
* [x] Add links to components and sponsors
* [x] ~~Reduce size of Spyder screenshot to avoid it cropping~~ Looks much too small on desktop, much more so than expected; recommend discussing this in a separate issue and addressing this in another PR by adding an abstract background (e.g. zoomed and blurred Spyder) and either reducing size as originally planned, switching to "cover" mode, and/or making the half-height breakpoint occur earlier
* [x] Change logo to raster and eliminate Blog
* [x] Copyedit mainpage text
* [x] Update screenshot in README

**Comment by ccordoba12** [comment]
Why this issue was closed by #184? It doesn't look right to me.

**Comment by CAM-Gerlach** [comment]
Accidentally used a trigger word out of context, sorry

![image](https://user-images.githubusercontent.com/17051931/98136637-c422d480-1e86-11eb-9175-0a244ca8749a.png)

**Comment by ccordoba12** [comment]
Ok, no prob.
