### ISSUE TITLE
Spyder on MacOS Mojave fails to launch 'Failed to copy signing info for'

### ISSUE THREAD

**Issue by deepcoder** [spyder-ide/website-spyder#194]
Spyder on MacOS Mojave fails to launch 'Failed to copy signing info for'

downloaded the Mac .dmg file from web site
https://github.com/spyder-ide/spyder/releases/latest/download/Spyder.dmg
put in applications directory

when launching, just shows dialog box with text 'Spyder Error'

Feb 12 10:33:10 graymini Spyder[18632]: Spyder Error
Feb 12 10:33:13 graymini com.apple.xpc.launchd[1] (org.spyder-ide.136728[18632]): Service exited with abnormal code: 255

Failed to copy signing info for 18673, responsible for file:///Applications/Spyder.app/Contents/MacOS/Spyder: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I wasn't aware of this limitation; this seems very severe and greatly limits the utility of our installer packages given that 10.14 is still supported by Apple (and Python, Anaconda and all deps I know of support much older versions, back to 10.9-10.11 at least in most cases) and was only first released two years ago, and 10.15 only supports Macs newer than mid 2012-late 2013. Moreover, last I heard we still had limitations in full support for Big Sur in the released version, leaving 10.15 as the single version fully supported. @mrclary could you clarify on this?

**Comment by mrclary** [comment]
let me see if I can fire up a VM with Mojave and investigate. I think in the worst case we could just build it on Mojave in our Pipeline...

**Comment by CAM-Gerlach** [comment]
Thanks. I do seem to remember something about normal macOS apps built with Xcode, that you can select a minimum macOS SDK version to build against and it will be compatible with later versions unless there are major API breaks, though I'm not that familiar with macOS development nor your particular packaging method.

**Comment by ccordoba12** [comment]
> I think in the worst case we could just build it on Mojave in our Pipeline...

This is really the problem: Github Actions don't have a Mojave image so we can't build our app on it. The oldest version available is Catalina. So I think the only possible workaround we could implement is telling Homebrew to compile things for Mojave (instead of using Catalina's bottles) or (somehow) trick it into believing it's running on Mojave.

**Comment by mrclary** [comment]
Hmm...I'm having trouble obtaining Mojave. Cannot get it from the App Store, or from the command line.

Tried special link here https://support.apple.com/en-us/HT211683, which results in 
<img width="500" alt="Screen Shot 2021-02-14 at 9 01 56 PM" src="https://user-images.githubusercontent.com/9618975/107907212-e3121780-6f07-11eb-9670-b1014f9b5865.png">

And command line:
```bash
>> softwareupdate --fetch-full-installer --full-installer-version 10.14.6
Downloading and installing 10.14.6 installer
SUPreferenceManager: Failed to set object of class: __NSCFConstantString for key: LastRecommendedMajorOSBundleIdentifier with error: Error Domain=SUPreferenceManagerErrorDomain Code=1 "(null)"
Installing: 100.0%SUPreferenceManager: Failed to set object of class: __NSCFConstantString for key: LastRecommendedMajorOSBundleIdentifier with error: Error Domain=SUPreferenceManagerErrorDomain Code=1 "(null)"
Install failed with error: Update not found 
```
I need to get a full version installer before I can try to make an image installer (iso) in order to create a VM.

**Comment by mrclary** [comment]
> > I think in the worst case we could just build it on Mojave in our Pipeline...
> 
> 
> 
> This is really the problem: Github Actions don't have a Mojave image so we can't build our app on it. The oldest version available is Catalina. So I think the only possible workaround we could implement is telling Homebrew to compile things for Mojave (instead of using Catalina's bottles) or (somehow) trick it into believing it's running on Mojave.

I wonder if something like this could work?
https://github.com/actions/virtual-environments/issues/1256#issuecomment-770270252

**Comment by mrclary** [comment]
@deepcoder or anyone with access to Mojave, could you test [this artifact](https://github.com/spyder-ide/spyder/suites/2045182010/artifacts/41167056)? It launches on Catalina and Big Sur, but I don't know if it made a difference for Mojave. It is the Lite version, but if it actually launches on Mojave, then I can build the full version and we can test that more extensively.

**Comment by CAM-Gerlach** [comment]
Hey @mrclary was this resolved?

**Comment by mrclary** [comment]
@CAM-Gerlach, I think the resolution is that there is no possible way for us to support Mojave. Github does not have a Mojave image for us to build the app on. I have detailed instructions for [building the app on macOS](https://github.com/spyder-ide/spyder/wiki/Dev:-Building-a-Standalone-Spyder-Application), so anyone should be able to download the latest source code and build on any macOS version they want.

See spyder-ide/spyder#15506 and spyder-ide/spyder#14756.

**Comment by CAM-Gerlach** [comment]
Gotcha, thanks, I understand. I left a comment over there as well. I guess once I fix the site build, we can add a line specifying minimum OS versions required, either static or conditional on the OS being detected. @ccordoba12 what's our minimum officially supported Windows version? 7? 8.1?

**Comment by CAM-Gerlach** [comment]
Hey @mrclary is there anything more to do about this on the website side?

**Comment by mrclary** [comment]
> Hey @mrclary is there anything more to do about this on the website side?

I don't think so. We can probably close this issue. Mojave is sufficiently ancient that I don't think we can do anything about it.

**Comment by CAM-Gerlach** [comment]
Okay, thanks Ryan! :+1:
