### ISSUE TITLE
Hero image/screenshot 10x+ larger than nominal (4.5+ MB) due to apparent scaling issue and resulting poor compression efficiency

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#202]
Following PR #199 , particularly what appeared to be its addressing of #197 , the size of the hero image has increased by 1000% (!), to a whopping 4.5+ MB. This is a very big hit for users, especially newer ones loading the site for the first time or that don't have access to good internet. Given the that both the image itself and the screenshot and logotype within are the same size and similar in content, and optipng barely made any difference (<3 % reduction), I strongly suspect the primary cause is the screenshot being rescaled by a non-integer multiple, one if not multiple times before appearing in the final rendered PNG. This results in very poor compression efficiency, as well as slightly inferior crispness and quality.

In order to fix this, the screenshot in the final hero graphic layout should be retaken or adjusted to be at a 1:1 ratio (100% size) to the original source, by sizing the Spyder window and display rendered resolution according. For reference, in the original I made, the screenshot was approximately 1770 x 780 (dimensions which were roughly maintained in the output by the current version); it doesn't have to be exactly those dimensions but it should be close enough that it can be added to the final layout at exactly 1:1 size. If for some reason that isn't possible, at the very least it should be a 2:1 ratio with nearest neighbor downsampling, though encoding performance and (to a lesser extent) quality will suffer somewhat.

In PR #199 , @isabela-pf graciously agreed to take this on at some point, so assigning this to her.

**Comment by conradolandia** [comment]
This is addressed by [PR 224](https://github.com/spyder-ide/website-spyder/pull/224). Format of image changed from png to webp, new image size is 271 KB.

**Comment by CAM-Gerlach** [comment]
This was fixed by #225 , so closing this. Thanks @conradolandia !
