### ISSUE TITLE
no-commit-to-branch is run when merging to master

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/website-spyder#204]
Builds are marked as broken thanks to that. See for example:

https://github.com/spyder-ide/website-spyder/runs/3683560773

**Comment by CAM-Gerlach** [comment]
Ah, this happens because the updated lint workflow I pulled in now runs on pushes to master, whereas it only ran on PRs before. I'll either disable the check or the job in that situation. Fix incoming ASAP.
