### ISSUE TITLE
Update binder link

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/website-spyder#209]
The link for starting Spyder on binder does not work. There is some explanation in https://github.com/spyder-ide/spyder/issues/19832#issuecomment-1287602906 and other comments on that issue.

**Comment by CAM-Gerlach** [comment]
We discussed it at the meeting, and @ccordoba12 will be addressing the issue linked there, but I'm not sure if we have an updated link we can add yet. However, we should update it on the docs too (and the Spyder Readme, etc), whenever we do get there.

**Comment by ccordoba12** [comment]
> but I'm not sure if we have an updated link we can add yet

Yes, we do and it's this one:

```
https://mybinder.org/v2/gh/spyder-ide/binder-environments/spyder-stable?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252FSpyder-Workshop%26urlpath%3Ddesktop%252F%26branch%3Dmaster
```

@CAM-Gerlach, could you take care of updating the Binder link here and in our docs? Thanks!

**Comment by CAM-Gerlach** [comment]
Sure; I've updated it here in #210 (as well as some other tweaks and updates to the Download section language, based on the feedback in spyder-ide/spyder-docs#334 ), and on the docs in spyder-ide/spyder-docs#336 .
