### ISSUE TITLE
Translate sections (home, community, downloads)

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/website-spyder#21]
We will have to wait https://github.com/goanpeca/spyder-website/pull/12  https://github.com/goanpeca/spyder-website/issues/15 and https://github.com/goanpeca/spyder-website/issues/20 before working in this issue

**Comment by CAM-Gerlach** [comment]
This seems to essentially duplicate the same fundamental issue of spyder-ide/spyder-website#8 , providing translations of the website, and these pages no longer exist in their current form, so closing this as a duplicate of that for now.
