### ISSUE TITLE
Use htmldity to reformat up the generated HTML content

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#34]
This is not important but it would be nice to reformat the built site so that the html follows a given convention.

We can use htmltidy for this.

**Comment by goanpeca** [comment]
@rlaverde

**Comment by goanpeca** [comment]
For example.. https://pypi.python.org/pypi/pytidylib

**Comment by rlaverde** [comment]
I think that the best way to integrate it will be as a plugin, there is already a plugin for a html minimizer [lektor-htmlmin plugin](https://github.com/vesuvium/lektor-htmlmin), maybe we could use this plugin, or write a new plugin for pytidylib

**Comment by goanpeca** [comment]
Sounds good

**Comment by rlaverde** [comment]
we could also try https://github.com/pietroalbini/lektor-minify

**Comment by goanpeca** [comment]
Ok. I trust your judgement on this :-)
