### ISSUE TITLE
Create a code examples section

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#39]
To make the transition easier for matlab users, we should do something like

https://www.mathworks.com/products/matlab/examples.html

**Comment by rlaverde** [comment]
I'm not sure if this  is a good idea, Matlab is a language and a set of libraries, but spyder is an IDE, maybe we could just add links to examples of the different libraries sites.

**Comment by goanpeca** [comment]
Matlab is a language a set of libraries and an IDE for the matlap language

Spyder is and IDE originally (and still) focused on python using several python libraries.

Having links to other libraries does not help people make the transition. People coming from matlab are not programming hackers used to going to N different websites.

**Comment by rlaverde** [comment]
Although I don't really like the idea (I think the right place for examples is each library site), I understand your point.

I will create a new section, I think we could reuse documentation template and model, Is that ok?

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by Nodd** [comment]
I agree with @rlaverde, spyder is not meant to replace the whole Matlab ecosystem. Continuum products would be a better target for this.
If you want a documentation for transition between both of them, have a look at https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.

**Comment by rlaverde** [comment]
Or maybe we could add examples about things that are exclusive of spyder, variable explores, cells.. etc

**Comment by CAM-Gerlach** [comment]
> variable explores, cells..

Given this is already covered by the documentation and I agree with those pointing out it really isn't Spyder's domain (we already get enough users asking us basic Python questions as it is; this would open the floodgates), should this be closed?

**Comment by ccordoba12** [comment]
Yeah, this is not something we should address.
