### ISSUE TITLE
File exchange anyone?

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#40]
http://www.mathworks.com/matlabcentral/fileexchange/?s_tid=gn_mlc_fx

**Comment by Nodd** [comment]
https://pypi.python.org/pypi ?
Yes Pypi is a mess, but so was file exchange last time I used it.

**Comment by rlaverde** [comment]
I'm not sure how this could be implemented, because we are using a static HTML generator,

We could create a new section with different subsections, but we will have to accept files through PRs :confused:

**Comment by goanpeca** [comment]
This is on hold for now in da Icebox ;-)

**Comment by ccordoba12** [comment]
I don't understand what this means. Closing.
