### ISSUE TITLE
Use i18n for translation

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/website-spyder#41]
As @goanpeca suggested in spyder-ide/website-spyder#36 the standard way to translate content is using i18n

There is a plugin for lektor https://github.com/numericube/lektor-i18n-plugin/ although is outdated and not working.

What we should do?

**Comment by CAM-Gerlach** [comment]
For now I'm closing this as a duplicate of spyder-ide/spyder-website#8 , as I've moved over the one bit of novel information over there and updated it for the present.
