### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/website-spyder#50]
There is a search box but It's not working

Search could be implement with an external service like google, or using a js librart like [tipue](https://github.com/Tipue/Tipue-Search), It will need a script (or lektor plugin) for serialize data.

**Comment by rlaverde** [comment]
https://github.com/rlaverde/lektor-static-search

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Now that the website (other than the blog) is a single page, and we have search on the docs where its most important, do we still want to do this? I could add support to the theme for a custom iframe inject where we want it and just copy and paste in the code from e.g. DuckDucGo, but we don't have a good place to put it other than the navbar, where it would be inconsistent with the docs and take up valuable space, and all it would search is the blogs which people can (and probably will) do with their favorite search engine anyway.

**Comment by ccordoba12** [comment]
Yeah, I don't think it's worth to invest time on this.
