### ISSUE TITLE
Organize the assets folder

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#6]
The asset folder has everything on one level and looks kinda messy. Any chance of adding folders and a better structure?

**Comment by rlaverde** [comment]
> The asset folder has everything on one level and looks kinda messy. 

I just follow the structure of the lektor-website, they put everything in the same folder (assets/static)

> Any chance of adding folders and a better structure?

yes
maybe something like this?
/assets/static/css
/assets/static/js
/assets/static/images

**Comment by goanpeca** [comment]
yes, much better, please do something like that
