### ISSUE TITLE
Create a carousel effect with some test images

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#7]
Like what the lektor page provides, 

You can use some images from here, https://github.com/spyder-ide/website/tree/master/img_src

**Comment by rlaverde** [comment]
I was thinking in use [slick library](https://kenwheeler.github.io/slick/), because foundation [Orbit](http://foundation.zurb.com/sites/docs/v/5.5.3/components/orbit.html) element is deprecated, is that ok? any suggestion?

**Comment by goanpeca** [comment]
Sure lets do that
