### ISSUE TITLE
Add download (Anaconda) and donate buttons to top bar, and darken font color

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/website-spyder#78]
@dalthviz or others, would you consider adding on the right of the top bar a download button linking to the Anaconda download page (similar in look to the current one for the source code buried down the page on a sub-tab), and secondarily a donate button linking to opencollective (like the one all the way at the buttom)? @ccordoba12 recommended I create a new issue to hopefully get it done.

These have been the top two requests on our gitter and other sources regarding even the small number of people who found the old website (especially the download button), so IMO it should be our highest priority to add to the top bar in some form ASAP considering that without them, the website serves essentially no purpose right now as users have no way to actually download and use spyder, and existing users no way to support the project (nor access any useful documentation, nor any direct link to our main github repo which we should probably stick on the top bar as well, or at least somewhere prominent).

Right now, there is no link *whatsoever* to download the recommended Anaconda version, and the only download link there is, the source download one, is buried a page down and under a subtab (which only a very, very small fraction of potential new users would actually want—and of those that do actually want to download source, they are way more likely to want to do so through git rather than a plain zip/tar—though many may not be aware of it). Furthermore, the donate button requires the user to scroll all the way to the bottom of the page, which is far from easy to find. 

Furthermore, can the text along the top bar (especially when not the selected section) be made much darker? Its very hard to read or even notice as is. Thanks.

**Comment by ccordoba12** [comment]
Closed by #85.
