### ISSUE TITLE
Enhance the footer (change template, add social media icons on footer)

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#9]
Add social media icons for spyder-ide on the footer

twitter: spyder_ide
facebook: https://www.facebook.com/SpyderIDE/
google: https://plus.google.com/u/0/communities/112932801653352854842
github: https://github.com/spyder-ide/spyder
gitter:  https://gitter.im/spyder-ide/public

**Comment by rlaverde** [comment]
There are already social media icons for github, github issues, twitter and gitter.
Is missing:
- facebook, google+ icons
- maybe change style to make them look bigger

**Comment by goanpeca** [comment]
Lets use this issue to enhance the footer, to look more like this

![image](https://cloud.githubusercontent.com/assets/3627835/17753469/9151fa7c-6495-11e6-9b54-5c231aa389d5.png)
