### ISSUE TITLE
Use the same shade of red everywhere

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/website-spyder#98]
The current color for icons, buttons, etc is a shade of orange that I think we took from the hugo-icon theme. However, this color is different from the snake color in the Spyder logo.

So the idea is to use the same shade of red everywhere (logo, icons, buttons, etc). Let's go with @jnsebgosselin's [suggestion](https://github.com/spyder-ide/spyder/pull/6909#issuecomment-379599860) of

    rgb(255, 33, 33).

@dalthviz, please work on this one.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, please also help us to update the banner with that color. @dalthviz will take care of the rest.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 In work now...will also push to the readmes after getting it done for the site itself.

**Comment by jnsebgosselin** [comment]
I may be just a typo on @ccordoba12  part, but my suggestion was  not `rgb(255, 33, 33)`, but `rgb(225, 33, 33)`.

![image](https://user-images.githubusercontent.com/10170372/38820420-d902d5bc-416b-11e8-986f-d7e276388846.png)

**Comment by jnsebgosselin** [comment]
The Open Collective banner is `rgb(210, 40, 40)` btw.

![image](https://user-images.githubusercontent.com/10170372/38821059-8597f13a-416d-11e8-96e6-49f633e5d7cf.png)

**Comment by ccordoba12** [comment]
Sorry, it was my mistake. I didn't copy the value from your comment correctly.

However, after seeing your three screenshots above, I think I like `255, 33, 33` better than `225, 33, 33`. The first one looks more vibrant.

@CAM-Gerlach, what do you think?

**Comment by ccordoba12** [comment]
> The Open Collective banner is rgb(210, 40, 40) btw.

We'll change that to use the same shade of red too.

**Comment by ccordoba12** [comment]
I tried `255, 33, 33` in several places in the website and it doesn't look good. I mean, it's too close to the Youtube icon color.

So I think we should go with @jnsebgosselin suggestion of `225, 33, 33`. @CAM-Gerlach, sorry for making you waste your time with this one.

**Comment by jnsebgosselin** [comment]
@ccordoba12 you are right. In retrospec, I also think that the `rgb(225, 33, 33)` looks too flat and I also agree that `rgb(255, 33, 33)` looks more vibrant.

Here is another test also with `rgb(238, 28, 36)`. 

![image](https://user-images.githubusercontent.com/10170372/38825265-f500b2b2-4179-11e8-8f40-aced1abe3410.png)

**Comment by jnsebgosselin** [comment]
> I tried 255, 33, 33 in several places in the website and it doesn't look good. I mean, it's too close to the Youtube icon color.

Ok, I understand. So it looks good when used only for the snake, but when there is too much of it, it is too flashy?

I've updated the image in my [comment](https://github.com/spyder-ide/website-spyder/issues/98#issuecomment-381682849) above to show better the various options we discussed so far.

**Comment by ccordoba12** [comment]
> but when there is too much of it, it is too flashy?

Yes. it's too flashy.

I'll try `238, 28, 36` and let you know.

**Comment by ccordoba12** [comment]
238, 28, 36: 

![seleccion_010](https://user-images.githubusercontent.com/365293/38825611-e2082f48-4172-11e8-97e9-50290ea066f7.png)

![seleccion_013](https://user-images.githubusercontent.com/365293/38825780-61c11baa-4173-11e8-96af-ffb0f0a88598.png)


225, 33, 33:

![seleccion_011](https://user-images.githubusercontent.com/365293/38825644-00912eb0-4173-11e8-9d08-03bbf71fdfd7.png)

![seleccion_014](https://user-images.githubusercontent.com/365293/38825792-69dd4ebc-4173-11e8-8dd4-133f14266f0f.png)

----

I think `238, 28, 36` looks better. @jnsebgosselin, what do you say? We need to decide this now because we need to make these changes today (please see Gitter about the reason).

**Comment by jnsebgosselin** [comment]
I think that both options look great. I'm undecided really...

My colleague who is doing a lot of web design said to me that the colors are not that important. It is the contrast between the different colors that is.

So I did some test here: https://contrastchecker.com/ to check the contrast between different shades of red and the gray color of the spyder web in the logo and here are the results:

`rgb(238, 0, 0)` vs `rgb(48, 48, 48)` : 2.91
`rgb(255, 33, 33)` vs `rgb(48, 48, 48)`  : 3.45
`rgb(238, 28, 36)`  vs `rgb(48, 48, 48)` : 3.03
`rgb(225, 33, 33)` vs `rgb(48, 48, 48)`  :  2.79

So I vote for `rgb(238, 28, 36)` because it makes the contrast of colors better in the logo, while not being too far away from the original design.

![image](https://user-images.githubusercontent.com/10170372/38825265-f500b2b2-4179-11e8-8f40-aced1abe3410.png)

**Comment by goanpeca** [comment]
My vote goes for `225, 33, 33:`

**Comment by jnsebgosselin** [comment]
These are additional tools that maybe can help you to choose... or not...

https://color.adobe.com
http://paletton.com

**Comment by ccordoba12** [comment]
Ok, thanks @jnsebgosselin! Then `238, 28, 36` it is.

@dalthviz, please use that color for our icons and links.

**Comment by CAM-Gerlach** [comment]
Sorry, just got to this after getting home form work; I was going to suggest something along these lines. I can't really tell the difference between the colors even right next to each other, but it makes the snake in the logo look much sharper. I'll implement momentarily and push all the changes again.

**Comment by CAM-Gerlach** [comment]
I take it we'll also be updating our logo itself in all the various places to match?

**Comment by ccordoba12** [comment]
Yes, we need to do that too.

**Comment by CAM-Gerlach** [comment]
I did it for the docs, and if you want I can do it for the banner image as well; I have both the logo and the text already for the former so I'd just need to reposition it for the latter. I could also ensure it was small caps like the banner for the reasons outlined in spyder-ide/spyder-docs#19 .
